import os
import asyncio
import pandas as pd
from gigease_financial_model import predict_worker_week
from gigease_rag_explainer import generate_claim_explanation

import sys
if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

async def run_inference_test():
    print("="*60)
    print("GIGEASE INFERENCE ENGINE TEST RUNNER")
    print("="*60)

    # 1. Load a test worker (T001 is Arun S, Velachery, STFI Claim Scenario)
    test_file = os.path.join(SCRIPT_DIR, "T001_enriched.csv")
    if not os.path.exists(test_file):
        print(f"Test file not found: {test_file}")
        return
        
    df = pd.read_csv(test_file)
    
    # 2. Let's find Week 5 (which is the first major flood week for T001)
    week_idx = 4 # 0-indexed, so index 4 is the 5th week
    test_row = df.iloc[week_idx].to_dict()
    
    print("\n[SCENARIO LOADED]")
    print(f"Worker: {test_row.get('worker_name')} (Zone: {test_row.get('primary_zone')})")
    print(f"Week: {test_row.get('week_start_date')}")
    print(f"Expected Income: {test_row.get('w_expected')} INR | Actual Income: {test_row.get('w_actual')} INR")
    
    print("\n[1] RUNNING FAST XGBOOST ML PIPELINE...")
    # 3. Feed it to the ML engine (should run under 50ms)
    prediction = predict_worker_week(test_row)
    
    print(f"  - Claim Trigger Probability: {prediction['claim_probability']:.2f} (Threshold: 0.50)")
    print(f"  - Claim Triggered (0/1):     {prediction['claim_triggered']}")
    print(f"  - Claim Payout Predicted:    {prediction['claim_amount_inr']:.2f} INR (ML/Formula Aligned)")
    print(f"  - Next Week Premium:         {prediction['weekly_premium_inr']:.2f} INR")
    
    print("\n[2] RUNNING ASYNC RAG + GEMINI EXPLAINER...")
    # 4. Feed the prediction into the Explainer
    explanation = await generate_claim_explanation(prediction, test_row)
    
    print("\n[FINAL APP NOTIFICATION GENERATED BY API]")
    print(f"Decision: {explanation['decision']}")
    print(f"Payout: {explanation['payout_inr']} INR")
    print("-" * 50)
    print(f"Short Reason: {explanation['reason_short']}")
    print(f"Detail Reason: {explanation['reason_detail']}")
    print("-" * 50)
    print(f"Note: {explanation['loading_note']}")

if __name__ == "__main__":
    asyncio.run(run_inference_test())
